<?php

$base = [
    'success_color' => '#22c55e',
    'warning_color' => '#f59e0b',
    'danger_color' => '#ef4444',
    'info_color' => '#3b82f6',
    'neutral_color' => '#6b7280',
    'heading_font' => 'Poppins',
    'body_font' => 'Poppins',
    'font_scale' => 1.0,
    'heading_weight' => 800,
    'body_weight' => 400,
    'letter_spacing' => 0.0,
    'line_height' => 1.5,
    'primary_button_text_color' => '#111111',
    'secondary_button_background' => '#111111',
    'secondary_button_text_color' => '#ffffff',
    'button_radius' => '1rem',
    'button_shadow' => '0 10px 25px rgba(0,0,0,.12)',
    'button_hover_animation' => 'translateY(-2px)',
    'card_background' => '#ffffff',
    'card_radius' => '1.5rem',
    'card_shadow' => '0 20px 40px rgba(0,0,0,.08)',
    'navbar_height' => 96,
    'navbar_background' => '#ffffff',
    'navbar_text_color' => '#111111',
    'navbar_hover_color' => '#facc15',
    'hero_overlay_color' => '#000000',
    'hero_overlay_opacity' => 40,
    'hero_gradient' => null,
    'footer_background' => '#000000',
    'footer_text_color' => '#ffffff',
    'footer_link_color' => '#9ca3af',
    'input_radius' => '1rem',
    'input_border_color' => '#d1d5db',
    'input_focus_color' => '#facc15',
    'container_width' => 1280,
    'section_padding' => 96,
    'spacing_scale' => 1.0,
    'sidebar_width' => 320,
    'animations_enabled' => true,
    'page_loader_enabled' => false,
    'scroll_reveal_enabled' => true,
    'dark_mode_enabled' => false,
    'dark_mode_toggle' => false,
    'dark_background' => '#111111',
    'dark_surface' => '#1f2937',
    'dark_text' => '#f9fafb',
];

$palette = static function (
    string $name,
    string $description,
    string $primary,
    string $secondary,
    string $accent,
    array $overrides = [],
) use ($base): array {
    return [
        'name' => $name,
        'description' => $description,
        'preview' => [$primary, $secondary, $accent],
        'tokens' => array_replace($base, [
            'primary_color' => $primary,
            'secondary_color' => $secondary,
            'accent_color' => $accent,
            'secondary_button_background' => $secondary,
            'navbar_background' => $accent,
            'navbar_text_color' => $secondary,
            'navbar_hover_color' => $primary,
            'footer_background' => $secondary,
            'input_focus_color' => $primary,
        ], $overrides),
    ];
};

return [
    'classic-gold' => $palette(
        'Classic Gold',
        'The established DK Singh gold, black, and white design system.',
        '#facc15',
        '#111111',
        '#ffffff',
    ),
    'modern-dark' => $palette(
        'Modern Dark',
        'A high-contrast dark interface with energetic gold accents.',
        '#ffd400',
        '#111111',
        '#18181b',
        [
            'card_background' => '#27272a',
            'navbar_background' => '#111111',
            'navbar_text_color' => '#fafafa',
            'footer_background' => '#09090b',
            'dark_mode_enabled' => true,
            'dark_mode_toggle' => true,
            'dark_background' => '#09090b',
            'dark_surface' => '#18181b',
            'dark_text' => '#fafafa',
        ],
    ),
    'minimal-white' => $palette(
        'Minimal White',
        'A restrained editorial palette with clean surfaces and compact depth.',
        '#111827',
        '#374151',
        '#ffffff',
        [
            'heading_font' => 'Inter',
            'body_font' => 'Inter',
            'button_radius' => '0.5rem',
            'card_radius' => '0.75rem',
            'button_shadow' => '0 2px 8px rgba(17,24,39,.10)',
            'card_shadow' => '0 8px 24px rgba(17,24,39,.06)',
            'section_padding' => 80,
        ],
    ),
    'corporate-blue' => $palette(
        'Corporate Blue',
        'A confident professional system built around clear blue and slate.',
        '#2563eb',
        '#0f172a',
        '#f8fafc',
        [
            'heading_font' => 'Inter',
            'body_font' => 'Inter',
            'info_color' => '#2563eb',
            'button_radius' => '0.625rem',
            'card_radius' => '1rem',
            'hero_gradient' => 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 100%)',
        ],
    ),
    'fitness-red' => $palette(
        'Fitness Red',
        'A bold, action-oriented fitness palette with strong red highlights.',
        '#ef4444',
        '#111827',
        '#ffffff',
        [
            'danger_color' => '#dc2626',
            'heading_weight' => 900,
            'button_radius' => '0.75rem',
            'hero_gradient' => 'linear-gradient(135deg, #111827 0%, #7f1d1d 100%)',
        ],
    ),
    'ocean-blue' => $palette(
        'Ocean Blue',
        'A fresh, accessible blue system inspired by open water and sky.',
        '#0ea5e9',
        '#0c4a6e',
        '#f0f9ff',
        [
            'info_color' => '#0284c7',
            'card_background' => '#ffffff',
            'hero_gradient' => 'linear-gradient(135deg, #0c4a6e 0%, #0ea5e9 100%)',
            'dark_background' => '#082f49',
            'dark_surface' => '#0c4a6e',
        ],
    ),
    'luxury-black' => $palette(
        'Luxury Black',
        'Premium black surfaces with refined metallic gold details.',
        '#d4af37',
        '#050505',
        '#111111',
        [
            'card_background' => '#181818',
            'navbar_background' => '#050505',
            'navbar_text_color' => '#f5f5f4',
            'footer_background' => '#000000',
            'heading_weight' => 700,
            'letter_spacing' => 0.4,
            'dark_mode_enabled' => true,
            'dark_mode_toggle' => true,
            'dark_background' => '#050505',
            'dark_surface' => '#181818',
            'dark_text' => '#f5f5f4',
            'hero_gradient' => 'linear-gradient(135deg, #050505 0%, #292524 100%)',
        ],
    ),
    'emerald' => $palette(
        'Emerald',
        'A balanced wellness palette using emerald, forest, and mint.',
        '#10b981',
        '#064e3b',
        '#ecfdf5',
        [
            'success_color' => '#059669',
            'hero_gradient' => 'linear-gradient(135deg, #064e3b 0%, #10b981 100%)',
            'dark_background' => '#022c22',
            'dark_surface' => '#064e3b',
        ],
    ),
    'purple-energy' => $palette(
        'Purple Energy',
        'An expressive, contemporary system with vivid violet energy.',
        '#8b5cf6',
        '#2e1065',
        '#faf5ff',
        [
            'hero_gradient' => 'linear-gradient(135deg, #2e1065 0%, #8b5cf6 100%)',
            'dark_background' => '#1e1b4b',
            'dark_surface' => '#2e1065',
        ],
    ),
    'sunset-orange' => $palette(
        'Sunset Orange',
        'A warm, optimistic palette with orange and deep terracotta.',
        '#f97316',
        '#7c2d12',
        '#fff7ed',
        [
            'warning_color' => '#ea580c',
            'hero_gradient' => 'linear-gradient(135deg, #7c2d12 0%, #f97316 100%)',
            'dark_background' => '#431407',
            'dark_surface' => '#7c2d12',
        ],
    ),
];
